services:
  - type: web
    name: train-status
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: INDIANRAIL_API_KEY
        value: 6bf43c622ca31f9e4f601f801bc94477
    autoDeploy: true
