services:
  - type: web
    name: train-status
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: RAPIDAPI_KEY
        value: 00c03ed5e2msh6d160394d303803p18ce05jsn4781667991f1
    autoDeploy: true
